# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_nubmer',
            new_name='phone_number',
        ),
    ]
