# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, max_length=100, verbose_name='식당위치'),
        ),
    ]
