# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170805_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default=1000, max_length=500, verbose_name='메뉴 가격'),
            preserve_default=False,
        ),
    ]
