# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_post_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.TextField(default=0, max_length=15, verbose_name='전화번호'),
            preserve_default=False,
        ),
    ]
