# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_post_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content3',
            field=models.TextField(default=0, max_length=300, verbose_name='영업 시간'),
            preserve_default=False,
        ),
    ]
